export const GET_CONSTRUCTOR_INGREDIENTS: 'GET_CONSTRUCTOR_INGREDIENTS' = 'GET_CONSTRUCTOR_INGREDIENTS';

export const ADD_CONSTRUCTOR_INGREDIENT: 'ADD_CONSTRUCTOR_INGREDIENT' = 'ADD_CONSTRUCTOR_INGREDIENT';
export const DELETE_CONSTRUCTOR_INGREDIENT: 'DELETE_CONSTRUCTOR_INGREDIENT' = 'DELETE_CONSTRUCTOR_INGREDIENT';
export const DELETE_ALL_CONSTRUCTOR_INGREDIENTS: 'DELETE_ALL_CONSTRUCTOR_INGREDIENTS' = 'DELETE_ALL_CONSTRUCTOR_INGREDIENTS';

export const CHANGE_ORDER_CONSTRUCTOR_INGREDIENTS: 'CHANGE_ORDER_CONSTRUCTOR_INGREDIENTS' = 'CHANGE_ORDER_CONSTRUCTOR_INGREDIENTS';

export const SET_BUN_TO_CONSTRUCTOR: 'SET_BUN_TO_CONSTRUCTOR' = 'SET_BUN_TO_CONSTRUCTOR';