export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const INCREASE_INGREDIENT_COUNT: 'INCREASE_INGREDIENT_COUNT' = 'INCREASE_INGREDIENT_COUNT';
export const DECREASE_INGREDIENT_COUNT: 'DECREASE_INGREDIENT_COUNT' = 'DECREASE_INGREDIENT_COUNT';
export const RESET_INGREDIENTS_COUNT_BY_TYPE: 'RESET_INGREDIENTS_COUNT_BY_TYPE' = 'RESET_INGREDIENTS_COUNT_BY_TYPE';
export const RESET_ALL_INGREDIENTS_COUNT: 'RESET_ALL_INGREDIENTS_COUNT' = 'RESET_ALL_INGREDIENTS_COUNT';