export const WS_CONNECTION_START_TO_ALL_ORDERS: 'WS_CONNECTION_START_TO_ALL_ORDERS' = 'WS_CONNECTION_START_TO_ALL_ORDERS';
export const WS_CONNECTION_START_TO_USER_ORDERS: 'WS_CONNECTION_START_TO_USER_ORDERS' = 'WS_CONNECTION_START_TO_USER_ORDERS';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_CONNECTION_CLOSE_BY_APP: 'WS_CONNECTION_CLOSE_BY_APP' = 'WS_CONNECTION_CLOSE_BY_APP';